import jsPDF from 'jspdf';

export function exportAsFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportPromptAsMarkdown(title: string, promptText: string, category: string, score?: number) {
  const dateStr = new Date().toISOString().split('T')[0];
  const markdown = `# ${title}
> Generated by PromptForge AI | Date: ${dateStr} | Category: ${category} ${score !== undefined ? `| Quality Score: ${score}%` : ''}

---

## Prompt Content

\`\`\`
${promptText}
\`\`\`

---
*Created with PromptForge AI — The Ultimate Prompt Engineering Studio*
`;

  const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  exportAsFile(markdown, `${safeTitle}_prompt.md`, 'text/markdown;charset=utf-8');
}

export function exportPromptAsTXT(title: string, promptText: string) {
  const text = `====================================================
PROMPTFORGE AI - EXPORT
Title: ${title}
Date: ${new Date().toLocaleDateString()}
====================================================

${promptText}

====================================================
Exported via PromptForge AI (https://promptforge.ai)
====================================================`;

  const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  exportAsFile(text, `${safeTitle}_prompt.txt`, 'text/plain;charset=utf-8');
}

export function exportPromptAsJSON(title: string, promptText: string, metadata: Record<string, any> = {}) {
  const data = {
    app: 'PromptForge AI',
    version: '1.0',
    exportedAt: new Date().toISOString(),
    title,
    prompt: promptText,
    metadata
  };

  const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  exportAsFile(JSON.stringify(data, null, 2), `${safeTitle}_prompt.json`, 'application/json;charset=utf-8');
}

export function exportPromptAsWord(title: string, promptText: string, category: string) {
  const htmlContent = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><title>${title}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 40px; }
      h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 8px; }
      .meta { color: #64748b; font-size: 14px; margin-bottom: 20px; }
      .prompt-box { background: #f8fafc; border: 1px solid #cbd5e1; padding: 20px; border-radius: 8px; font-family: monospace; white-space: pre-wrap; }
      .footer { margin-top: 40px; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="meta">Category: <b>${category}</b> | Exported: ${new Date().toLocaleDateString()}</div>
      <div class="prompt-box">${promptText.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
      <div class="footer">Exported from PromptForge AI — The Ultimate Prompt Engineering Studio</div>
    </body>
    </html>
  `;

  const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  exportAsFile(htmlContent, `${safeTitle}_prompt.doc`, 'application/msword');
}

export function exportPromptAsPDF(title: string, promptText: string, category: string, score?: number) {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // Header
    doc.setFillColor(99, 102, 241); // Indigo
    doc.rect(0, 0, 210, 24, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('PromptForge AI Studio', 14, 15);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 160, 15);

    // Title
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 14, 38);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Category: ${category} ${score !== undefined ? `| Quality Score: ${score}%` : ''}`, 14, 45);

    // Divider
    doc.setDrawColor(226, 232, 240);
    doc.line(14, 49, 196, 49);

    // Prompt content box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 54, 182, 200, 3, 3, 'FD');

    doc.setTextColor(30, 41, 59);
    doc.setFontSize(10);
    doc.setFont('courier', 'normal');

    const splitText = doc.splitTextToSize(promptText, 174);
    doc.text(splitText, 18, 62);

    // Footer
    doc.setTextColor(148, 163, 184);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.text('Generated with PromptForge AI — Create Better Prompts. Build Smarter AI.', 14, 285);

    const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, '_');
    doc.save(`${safeTitle}_prompt.pdf`);
  } catch (err) {
    console.error('PDF Export Error:', err);
    // Fallback to text export if PDF fails
    exportPromptAsTXT(title, promptText);
  }
}
